import '@styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Bluray list',
	description: 'Generated by jeyofdev',
};

type RootLayoutPropsType = {
	children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutPropsType) => {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
