import { CssBaseline } from '@mui/material';
import '@styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import RootComponent from '../components/RootComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Bluray list',
	description: 'Generated by jeyofdev',
};

type RootLayoutPropsType = {
	children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutPropsType) => {
	return (
		<html lang='en'>
			<RootComponent>
				<CssBaseline />
				<body className={`${inter.className} bg-gray-50`}>{children}</body>
			</RootComponent>
		</html>
	);
};

export default RootLayout;
